apiVersion: v1
kind: Service
metadata:
  name: {{ include "wdemo-fe.fullname" . }}
  labels:
    {{- include "wdemo-fe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    {{- include "wdemo-fe.selectorLabels" . | nindent 4 }}
