extraEnvVars:
  - name: ELASTICSEARCH_HOST
    value: "elasticsearch-dew.default.svc.cluster.local"

input: |-
  http { port => 8080 }
  beats { port => 5044 }

output: |-
  elasticsearch {
    hosts => ["http://elasticsearch-dew.default.svc.cluster.local:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
    action => "create"
  }

containerPorts:
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: monitoring
    containerPort: 9600
    protocol: TCP
  - name: beats
    containerPort: 5044
    protocol: TCP

service:
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: beats
      port: 5044
      targetPort: beats
      protocol: TCP
